server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_service?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ditrionD1
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
